<?php include '_header.phtml'; ?>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/git">GIT Manager</a>
    </div>
    <!-- <div id="navbar" class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
      </form>
    </div> --><!--/.navbar-collapse -->
  </div>
</nav>

<div class="container container-fluid" style="margin: 30px 0px;">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
        <?php if (isset($error) && $error) {?>
			<div class="alert alert-danger alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Oops!</strong> <?echo $error; ?>
			</div>
        <?php } ?>
			<form role="form" class="form-horizontal" method="POST">
				<div class="form-group">
					<label for="exampleInputEmail1" class="col-md-2">
						Email
					</label>
                    <div class="col-md-10">
					   <input type="email" name="email" value="<?echo isset($login_email) ? $login_email : ''; ?>" class="form-control" id="exampleInputEmail1">
                    </div>
				</div>
				<div class="form-group">

					<label for="exampleInputPassword1" class="col-md-2">
						Password
					</label>
                    <div class="col-md-10">
					   <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>
				</div>
				<button type="submit" class="btn btn-default">
					Submit
				</button>
			</form>
		</div>
	</div>
    <hr>

    <footer>
        <p>&copy; DEV System</p>
    </footer>
</div>

<?php include '_footer.phtml'; ?>
